import { Component } from '@angular/core';
// Define the Project type
interface Project {
  image: string;
  title: string;
  location: string;
  siteCrew: number;
  projectManagers: number;
}
@Component({
  selector: 'app-services',
  imports: [],
  templateUrl: './services.component.html',
  styleUrl: './services.component.css',
})
export class ServicesComponent {
  projects: Project[] = [
    {
      image: './assets/images/1.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 3,
    },
    {
      image: './assets/images/2.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 3,
    },
    {
      image: './assets/images/3.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/4.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 3,
    },
    {
      image: './assets/images/5.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 3,
    },
    {
      image: './assets/images/6.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/7.jpg',
      title: 'Sharjah',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 12,
      projectManagers: 3,
    },
    {
      image: './assets/images/8.jpg',
      title: 'Sharjah',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/9.jpg',
      title: 'Sharjah',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/10.jpg',
      title: 'Sharjah',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 12,
      projectManagers: 3,
    },
    {
      image: './assets/images/11.jpg',
      title: 'Sharjah',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/12.jpg',
      title: 'Sharjah',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/13.jpg',
      title: 'Sharjah',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/14.jpg',
      title: 'Sharjah',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/15.jpg',
      title: 'Sharjah',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/16.jpeg',
      title: 'Sharjah',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/17.jpeg',
      title: 'Dubai',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/18.jpeg',
      title: 'Dubai',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/19.jpeg',
      title: 'Dubai',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/20.jpeg',
      title: 'Dubai',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/21.jpeg',
      title: 'Dubai',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/22.jpeg',
      title: 'Dubai',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/23.jpeg',
      title: 'Dubai',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/24.jpeg',
      title: 'Dubai',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/25.jpeg',
      title: 'Dubai',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/26.jpeg',
      title: 'Dubai',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/27.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/28.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/29.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/30.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/31.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/32.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/33.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/34.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/35.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/36.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/37.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/38.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
    {
      image: './assets/images/39.jpeg',
      title: 'Ajman',
      location: 'Building excellence through experience, safety, and reliability',
      siteCrew: 15,
      projectManagers: 2,
    },
  ];
}
